alter table WORKSHOP_SPECIAL_OFFER add constraint FK_WORKSHOP_SPECIAL_OFFER_SERVICE foreign key (SERVICE_ID) references WORKSHOP_SERVICE(ID);
create index IDX_WORKSHOP_SPECIAL_OFFER_SERVICE on WORKSHOP_SPECIAL_OFFER (SERVICE_ID);
