-- begin WORKSHOP_CLIENT
create unique index IDX_WORKSHOP_CLIENT_UNIQ_PHONE_NUMBER on WORKSHOP_CLIENT (PHONE_NUMBER) where DELETE_TS is null ^
create unique index IDX_WORKSHOP_CLIENT_UNIQ_EMAIL on WORKSHOP_CLIENT (EMAIL) where DELETE_TS is null ^
-- end WORKSHOP_CLIENT
-- begin WORKSHOP_MECHANIC
alter table WORKSHOP_MECHANIC add constraint FK_WORKSHOP_MECHANIC_USER_ID foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_WORKSHOP_MECHANIC_USER on WORKSHOP_MECHANIC (USER_ID)^
-- end WORKSHOP_MECHANIC
-- begin WORKSHOP_SPARE_PARTcreate unique index IDX_WORKSHOP_SPARE_PART_UK_TITLE1 on WORKSHOP_SPARE_PART (TITLE) where DELETE_TS is null ^
-- end WORKSHOP_SPARE_PART
-- begin WORKSHOP_ORDERalter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_CLIENT foreign key (CLIENT_ID) references WORKSHOP_CLIENT(ID)^
alter table WORKSHOP_ORDER add constraint FK_WORKSHOP_ORDER_MECHANIC foreign key (MECHANIC_ID) references WORKSHOP_MECHANIC(ID)^
create index IDX_WORKSHOP_ORDER_MECHANIC on WORKSHOP_ORDER (MECHANIC_ID)^
create index IDX_WORKSHOP_ORDER_CLIENT on WORKSHOP_ORDER (CLIENT_ID)^
-- end WORKSHOP_ORDER
-- begin WORKSHOP_ORDER_SPARE_PART_LINK
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_WOSPL_ORDER foreign key (ORDER_ID) references WORKSHOP_ORDER(ID)^
alter table WORKSHOP_ORDER_SPARE_PART_LINK add constraint FK_WOSPL_SPARE_PART foreign key (SPARE_PART_ID) references WORKSHOP_SPARE_PART(ID)^
-- end WORKSHOP_ORDER_SPARE_PART_LINK
-- begin WORKSHOP_SERVICE
create unique index IDX_WORKSHOP_SERVICE_UK_TITLE on WORKSHOP_SERVICE (TITLE) where DELETE_TS is null ^
-- end WORKSHOP_SERVICE
-- begin WORKSHOP_ORDER_SERVICE_LINK
alter table WORKSHOP_ORDER_SERVICE_LINK add constraint FK_WOSL_ORDER foreign key (ORDER_ID) references WORKSHOP_ORDER(ID)^
alter table WORKSHOP_ORDER_SERVICE_LINK add constraint FK_WOSL_SERVICE foreign key (SERVICE_ID) references WORKSHOP_SERVICE(ID)^
-- end WORKSHOP_ORDER_SERVICE_LINK
-- begin WORKSHOP_SPECIAL_OFFER
alter table WORKSHOP_SPECIAL_OFFER add constraint FK_WORKSHOP_SPECIAL_OFFER_SERVICE foreign key (SERVICE_ID) references WORKSHOP_SERVICE(ID)^
create index IDX_WORKSHOP_SPECIAL_OFFER_SERVICE on WORKSHOP_SPECIAL_OFFER (SERVICE_ID)^
-- end WORKSHOP_SPECIAL_OFFER
